### ISSUE TITLE
Door locks are not shared on top and bottom

### ISSUE THREAD

**Issue by GriffinCodes** [pop4959/LWCX#107]
**LWC Version (/lwc admin version):** 
![image](https://user-images.githubusercontent.com/12417961/83997543-9c0d6480-a92c-11ea-86ee-20eeba2a0a62.png)

**Server version (/version):** 
![image](https://user-images.githubusercontent.com/12417961/83997617-c828e580-a92c-11ea-9dff-e68bc228e876.png)

**Short five word summary of issue:** Door locks are not shared on top and bottom

**Detailed description of problem:**
Some doors (so far, afaict, only legacy doors from 1.12 using the [dmulloy2 fork, pre entity changes with small additions](https://github.com/Pugabyte/LWC)) do not share their locks between the top and bottom section. Clicking on the top part will not prevent the event, and will not trigger the double door feature, but clicking on the bottom will do both of those.

[Database entry of affected door](https://paste.bnn.gg/okepo.json)
[Video example](https://www.youtube.com/watch?v=p01HAOXr8E0)

`/cinfo`
![image](https://user-images.githubusercontent.com/12417961/83997878-6c129100-a92d-11ea-8bc8-260889713862.png)

There are no protections at y += 1 of this protection

**Comment by pop4959** [comment]
This is a known problem currently with servers utilizing a (possibly old) MySQL database on LWC 2.2.5. I need to look into this some more, but it was apparently caused by 4acf69e627e0118ad68f3e1727cabd9d6e8cc2cd. For now, if anyone has this issue, please download the patched version of 2.2.5 below that reverts this change.

https://cdn.discordapp.com/attachments/481962752924188692/707369614979498024/LWCX-2.2.5.jar

**Comment by pop4959** [comment]
I've finally been able to get access to a MySQL database to test this, but I'm not able to replicate the issue. Can you add me on Discord pop4959#1781 so that we can try to figure out what is different on your end?

**Comment by Doctacosa** [comment]
We also seem to have this one after migrating to 1.16, we're running version 2.2.6-2d10269. Interesting bugger!

I've got one oak door where the top is unprotected, and the bottom protected.
I also have an iron door where the top and bottom parts are protected to two different players.

In our case, we don't use MySQL, it's in a SQLite database. It was first created in late 2011 or early 2012 and kept running since, from LWC to ModernLWC to LWCX. I'm not sure if that could be a factor. I'm willing to provide the file and matching coordinates if you want to give it a look.

**Comment by pop4959** [comment]
@Doctacosa That would be superb! If you can, please add me on Discord or join the support channel linked from the plugin page. If you are able to provide the sqlite file and any world region files associated with strange protections that would be of great help.

I also have an updated version of the aforementioned patch for LWCX 2.2.6 / MC 1.16, which is linked in the Discord channel for anyone who is helping test the problem,

**Comment by pop4959** [comment]
I've fully reverted the aforementioned commit for now since there has been substantial evidence for it causing this issue, however strangely I have never found a way to reproduce it, even using the exact database and map for people having it. You can safely use the latest dev build and doors *should* be working again as they were normally before 2.2.5.

**Comment by WakkaFlocka239** [comment]
We're still experiencing this on Paper 1.16.4, LWCX v. 2.2.6

LWC version
<img src=https://i.imgur.com/sYdFSiy.jpg>

Server version
<img src=https://i.imgur.com/wvbFHiw.jpeg>

**Comment by pop4959** [comment]
@WakkaFlocka239 The current release 2.2.6 would still be affected. This was reverted in 2.2.7 development builds. You can get it from any of the mirrors linked on the plugin page. :)
