### ISSUE TITLE
LWC WG claims

### ISSUE THREAD

**Issue by ArcLP** [pop4959/LWCX#11]
**LWC Version (/lwc admin version):** 
2.1.7-d645514
**Server version (/version):** 
git-Paper-140 (1.14.4)
**Short five word summary of issue:** 
LWC not removed when Region deleted
**Detailed description of problem:**

LWC protections stay when worldguard regions are deleted (via thirdparty plugin; Guilds)

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
It looks like there is a command, `/lwc admin purgeregion <region> <world>` that will remove the protections in a WorldGuard region, but it is not automatic as far as removing them when a third party plugin is involved such as Guilds. This would likely require the third party plugin to add an integration with LWC to remove the protections when it removes the region.

**Comment by pop4959** [comment]
Protections will never be removed by LWC automatically due to another plugin removing the chests, as it is the responsibility of the respective plugins to remove those protections if necessary. Removing them automatically might not be desirable on all servers, and can cause more harm than good. LWC has the capability of removing protections by region and through admin cleanup, to cover any lack of explicit support in other plugins, so I think this issue can safely be closed.
