### ISSUE TITLE
(small) alias "/chopperin" and "/chopperout" aren't exist

### ISSUE THREAD

**Issue by RedstoneFuture** [pop4959/LWCX#110]
**LWC Version (/lwc admin version):** 2.2.5-67bdb89
**Server version (/version):** 1.13.2

**Short five word summary of issue:** 

In the wiki you listed the alias "/chopperin" and "/chopperout" for the flag-command (_/lwc flag hopperin_ + _/lwc flag hopperout_) but in your code this alias aren't defined.

https://github.com/pop4959/LWCX/wiki/Commands#protection-flags

**Comment by pop4959** [comment]
Thanks for pointing that out, it is an error in the documentation, most likely due to copy/paste. I've purposefully not created aliases for those, because most players are already confused enough about the functionality of the hopper flag. The hopperin and hopperout flags are meant for more technical users who want to control hopper flow in a single direction. It does still create a minor inconsistency, so I've wondered if this was the right decision, although it can easily be changed in the future.

By the way, thanks for helping fix issues in the documentation. You might have noticed I also reverted one of your edits. The reason was because it broke some of the formatting, and incorrectly changed some information about rights modification (specifically, removing information about it from cmodify, where it is most relevant, and instead calling them "destrictions", which is not terminology that is used in LWC).

I recently a few hours refactoring the commands page, so it should be organised appropriately, unlike some other parts of the wiki which may still be largely unchanged from Hidendra's. I would appreciate it if you can bring up any large changes with me either here through an issue, or directly on Discord (preferred), so that we can discuss what would be the best course of action.

**Comment by RedstoneFuture** [comment]
Ah ok, all right. :)
