### ISSUE TITLE
/lwc admin cleanup only check 250 protection even thought they are more protection are present

### ISSUE THREAD

**Issue by TetraTheta** [pop4959/LWCX#117]
**LWC Version (/lwc admin version):** 2.2.6-2d10269
**Server version (/version):** git-paper-127 (MC: 1.16.1)

**Short five word summary of issue:**  
`/lwc admin cleanup` only checks 250 protections even though there are 501 protections in my server

**Detailed description of problem:**  
![IMG1596033662](https://user-images.githubusercontent.com/37061801/88814404-ffad6300-d1f4-11ea-81b0-74d68b96d751.png)  
LWC only checks 250 protections but I want LWC to check all of its protection(currently 501) but I cannot find any way to achive that. Is this intended, or bug? I don't care checking more than 250 protections causes server to lag a bit because I run this command when nobody in server except me. 

`cacheSize` is 10000 which is default value, and `precache` is `-1` which is also default value.

PS. a small question: what is difference between 'Modern LWC' and 'LWC Extended'? 'Modern LWC' has github link to 'LWC Extended' repository in Spigot Resources page.

**Comment by pop4959** [comment]
It's probably not an issue; may have to do with cache. Most likely some protections were skipped because they didn't need to be checked.

`/lwc admin cleanup` takes a while to run and causes some lag because it actually loads the chunks for every protection in the database, to check if the block is still there. If the block is not physically present anymore, it's marked as non existent and is removed from the database. It's probably good that you do this only during maintenance. It also generally doesn't need to be run often (usually only when you've done a lot of work with other plugins removing blocks like WorldEdit).

`cacheSize` determines the maximum number of protections that can be loaded into memory (RAM). This allows LWC to bypass potentially expensive database lookups. With `precache` is set to `-1`, then the server starts up it will try to load protections up to the cache limit into memory at startup. If the number is higher than the number of protections on the server (as in your case), then every protection in the world will be loaded at all times, and the only time it needs to access the database is when it needs to update it.

I am the author of updates to both Modern LWC 2.1.0-2.1.5 and LWC Extended 2.1.6--. The former is no longer receiving updates due to unfortunate circumstances revolving around the person who owns that plugin page. LWC Extended is on a new plugin page, with a different name, but receiving the exact same updates that would have been posted to the old page.

If you have any additional questions, feel free to also visit our Discord server!
