### ISSUE TITLE
Cleanup world limits & TPSKeep

### ISSUE THREAD

**Issue by kotarobo** [pop4959/LWCX#124]
**Short five word summary of issue:** 
Cleanup world limits & TPSKeep
**Detailed description of problem:**
I want to use the /lwc admin cleanup to periodically reset certain worlds, but it's heavy because it surveys all worlds.
Is it possible to specify a world?
I'd also like to change the survey speed because chunk loading is heavy or TPS goes down to 3.

**Comment by pop4959** [comment]
The reason why it's heavy is that it has to load all of the chunks in the world that contain protections. This isn't really going to change, since there isn't a way to avoid that. Though, you shouldn't lose TPS if you are using Paper on a recent version of the game, because chunk loading is async, so this shouldn't be as much of an issue as it's made out to be (but it'll still take some time).
