### ISSUE TITLE
bindMessageCache doesn't expire values

### ISSUE THREAD

**Issue by aurorasmiles** [pop4959/LWCX#130]
**LWC Version (/lwc admin version): 2.2.6** 
**Server version (/version):** 1.16.3 Paper 231

**Short five word summary of issue:** 
 
> holy shit yeah that's super huge

**Detailed description of problem:**

The bindMessageCache in https://github.com/pop4959/LWCX/blob/master/src/main/java/com/griefcraft/lwc/SimpleMessageParser.java does not expire values, creating huge HashMaps over time, mostly with the key "lwc.time.pasttime" for me (size over 4.6 million)
This has the nice result of taking over a gigabite of memory after a few days :D

**Comment by pop4959** [comment]
Should be fixed in the latest dev build (which you can grab from [here](https://papermc.io/ci/view/%20%20Plugins/job/LWCX/145/)).

I've changed it to use an LRU cache with a maximum capacity of 1000 instead of the Hash map. Not sure if this is going to be too small, so I'd recommend that you check `/lwc debug` after using this for a while and report back how many cache hits and misses you are seeing so I can adjust it as necessary. I'll be doing the same on my own server.

Thanks again for bringing this to my attention.
