### ISSUE TITLE
Suggestion: Command to open a locked container(chest, barrel) without removing the lock and without the ability to put items in or out

### ISSUE THREAD

**Issue by JaHollTV** [pop4959/LWCX#136]
Suggestion:
Command list /copen
With a rightclick you can open a protected chest. But you cannot put items in or get items out. For that you need an extra perm.

Example Perms:
copen:                          lwc.copen
copen put items in:      lwc.copen.putin
copen put items out:   lwc.copen.putout

**Comment by pop4959** [comment]
Sounds like you want a display chest. You can create one with `/cdisplay` or change an existing protection to a display protection with `/cmodify display`. If not, find an appropriate protection type & make proper modifications.

Adding permissions to access chests like you are suggesting will not be done since this completely bypasses the protection system as it is intended to be used. If you wish to do this, there is already an option if you are an LWC admin with `/lwc admin view` (or just opening the chest normally).

**Comment by JaHollTV** [comment]
@pop4959 So i have a Roleplay Server. Police Officer should open chests, when the have a Perm, but not put things out or in, cause of griefing and so on.

/cdisplay & /cmodify display works fine. But normal players just protect the chest as private.
So could you add a Command with that a Player(with permission) can open 1 chest in displaymode even if the chest is private?

/lwc adminv view ID works. but a player doesnt have the ID
