### ISSUE TITLE
Feature Request: Allow Hopper In, Not Out

### ISSUE THREAD

**Issue by k9lego** [pop4959/LWCX#14]
Just a pretty quick idea here. It’d be nice if you could allow hoppers to put items in, e.g. a farm, and not allow hoppers to take items out, e.g. a griefer placed a hopper under the chest to get items from it. 
I do apologize if this is already a feature, didn’t get a chance to see if the plugin has that feature (and I’m stuck on mobile rn). Ty!

**Comment by pop4959** [comment]
Yeah I think this has already been suggested 1 or 2 times, and it's not a bad idea. Pretty sure it's not a feature currently because the "denyHoppers" option and the hopper flag just turn interactions on/off in general, not specifically in/out.

**Comment by pop4959** [comment]
I was talking to someone about this earlier, and I guess the blacklist does a fine job for the example your provided. By default, it has hoppers on it which prevents people from placing hoppers adjacent to protections they don't own (which means it would not be able to be easily stolen as you're suggesting). Is there any other reason to want specifically an in/out? Just debating on whether it really makes sense to add new flags, etc, for this, if it's to little effect.

**Comment by OutlawedBit** [comment]
Per my previous request (#86) from the other plugin, I would still like to see this feature as well.  I have a few machine builders in my user base who appreciate the option to allow a hopper to anonymously drop items into protected chest.

**Comment by pop4959** [comment]
If this were to be added in some form, I'm guessing it would best be through the existing flag system. Since there is currently a /cHopper flag, do you think it would be good if 2 new flags were added for this, such as /cHopperIn and /cHopperOut? That might be the easiest way to handle this that would make sense to users who are already used to how the old flag works.

**Comment by OutlawedBit** [comment]
Yeah, I think that would be great.  I can't immediately think of a good reason to have the cHopperOut, but I sure someone else could.

**Comment by k9lego** [comment]
Protecting item transport tubes?

**Comment by pop4959** [comment]
@k9lego @OutlawedBit 

Implemented this in d70d124415458ea48116f7070ba45db2c341320f. Some notes about the new flags:

- Existing Hopper flag is equivalent to the HopperIn and HopperOut flags combined.
- The `protections.denyHoppers` setting in core.yml can flip the meaning of the HopperIn and HopperOut flags, as it does currently for the Hopper flag.
- There is no shortcut command (use `/lwc flag <flag> <on/off>` instead). It may not need one since this is a niche use case.
- It does not currently work if `optional.alternativeHopperProtection` is enabled in core.yml. This is because it works very differently from the normal hopper checking mechanism (on placement rather than inventory movement).

I've tested it a bit myself, but further help testing would be appreciated. Let me know if it works as expected for you. You can find development builds linked on the plugin page as usual.
