### ISSUE TITLE
LWC plugin does not start with towny

### ISSUE THREAD

**Issue by Mundo-Minecraft** [pop4959/LWCX#154]
LWC Version 2.2.8 Build #156
Server Version 1.16.5, Paper #714
Towny Version 0.95.1.8

LWC plugin does not start with towny

The LWC plugin does not start when the Towny plugin is active. It indicates the following: https://pastebin.com/X4Fr19HV (option townBorders: false in towny.yml)
If I disable towny LWC it works correctly again. With the same version of towny (0.95.1.8), paper #568 and LWC 2.2.7 everything works fine.

Thanks greetings.

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
The Towny integration in LWC 2.2.7+ was recently updated by LlmDl (the Towny developer) to require Towny 0.96.7.0. This was done due to API changes which caused issues with un-claiming in newer versions, and is not a bug.

Your options are to use an older version of LWC (2.2.6-), or update Towny (0.96.7.0+).
