### ISSUE TITLE
Protection of turtle eggs incomplete

### ISSUE THREAD

**Issue by LadyCailin** [pop4959/LWCX#171]
**LWC Version (/lwc admin version):** 4.5.0-SNAPSHOT
**Server version (/version):** 1.16

**Short five word summary of issue:** Protection of turtle eggs incomplete

**Detailed description of problem:**
1. Turtle eggs can be protected, but even when protected, but can still be trampled.

2. Furthermore, when turtles hatch, the lock remains on that block space, so future placements of eggs (and presumably other lockable items) by other players will cause the eggs to be locked by the player who placed the egg the first time.

**Comment by pop4959** [comment]
There are a large number of missing matchers in LWC for things like these - and I don't think it's generally something worth fixing at this point due to the amount of effort it would require.

That said, I am not closing this without an alternative. [Bolt](https://github.com/pop4959/Bolt/wiki) has matchers for every block in the game, not just containers. I think if you take a look there you'll be pleasantly surprised. This plugin can be thought of as an up and coming replacement for LWC (which already does most things better that LWC already has).

PS: Alternative to cdefaults coming soon in Bolt as well, in case that is something you still need too. If you'd like to chat about it more you can reach out on Discord: pop4959#1781. Let me know what your username is if it's different than here.
