### ISSUE TITLE
Add an option to disable inheritance in limitsv2.yml

### ISSUE THREAD

**Issue by JohOply** [pop4959/LWCX#20]
**Short five word summary of issue:** Add an option to disable inheritance in limitsv2.yml

**Detailed description of problem:**

Quote from discussion with pop
> I think I see what you meant about the inheritance now. Most people (including myself) probably find that fairly intuitive because it works just like their permission system does. However I agree that it is a bit less flexible than a permission system, so perhaps an option would be useful for people who want to manually set it per group.

**Comment by pop4959** [comment]
I looked into the code, and this doesn't seem to be possible currently. LWC is only able to obtain a list of groups that a user belongs to. So there isn't really a way to only use one group as the user's limits.

Your workaround (using permission groups that are not set up in a hierarchy) is probably the best way to do this right now. Otherwise, you do have to deal with inheritance as usual.
