### ISSUE TITLE
Ceiling Redstone Mechanics Not Locking Blocks

### ISSUE THREAD

**Issue by andrewkm** [pop4959/LWCX#204]
**LWC Version (/lwc admin version):** 2.2.9-dev-bdf31cc (Latest)
**Server version (/version):** Paper 1.19.1 Build 96

**Short five word summary of issue:** 
Ceiling Redstone Mechanics Not Locking Blocks

**Detailed description of problem:**

**Taken from a bug report on our site**:
(https://ecocitycraft.com/forum/threads/ceiling-redstone-mechanics-not-locking-blocks.218035/)

**Brief Description**: Placing redstone interactable blocks (stone button and lever were used to test this) on the bottom of a block and locking them does not protect the block from being broken. In my testing we used a diamond block, and placed a button on the side and top and put a /lock on it. Doing it on the side or top like this causes the diamond block to also become locked, and is then unbreakable by others. Placing the lockable item on the bottom (or "ceiling") of the block does not lock the block that it is on, however it will lock the block below it that it isn't actually attached to at all.

**Instructions**: Place a lockable redstone interactable on the bottom (or ceiling) of a block and /lock it. This will not lock the block that it is attached to, but will lock the one right below it only if you punch said block before breaking the block with the redstone interactable on it. Then, if someone breaks the block with the button attached (which they can do if they have perms to that town/plot, because the button/lever does not lock the block it's attached to) it will leave a locked block below it that should not be possible to be locked by any other method.

**How many times did you recreate this?**: 5+

**Result**: It is possible to lock blocks that otherwise shouldn't be able to be locked, and the redstone interactable is not locking the block that it should.

**Expected Result**: The bottom block shouldn't get locked like this (even if it only happens when it's interacted with before the top block is broken) and the top block should be locked.

**Video**: https://www.youtube.com/watch?v=Pev1Nsh9CmY

**Comment by pop4959** [comment]
I'm surprised this has been a bug for so long. I don't have time to look into this immediately but my assumption is that since top/bottom facing buttons did not exist until a relatively recent MC version, LWC just does not handle these.

**Comment by pop4959** [comment]
LWC doesn't really have the proper matchers to support this (or a million other things), so while I had interest in fixing this originally I don't anymore unfortunately.

For better support with non-container matchers, I recommend switching over to [Bolt](https://github.com/pop4959/Bolt/wiki), which aims to be a full alternative to LWC (and more). It already has matchers for every block in the game unlike LWC. Needless to say, this button issue is fixed, plus levers, plus any other thing you could even think of protecting.

Of course, I know you've got a big server andrew so if for some reason you find that it isn't possible for you to use Bolt instead of LWC at the moment please let me know why and I can work with you to make it happen. Most of my efforts now are spent on porting everything and extending the base feature set so that it far supersedes what LWC is capable of.

Feel free to reach out on the LWC Discord (there is further announcements there about Bolt) or message me directly (pop4959#1781) if you want to chat about it more. Thanks!

**Comment by andrewkm** [comment]
Thank you for keeping me updated.
It's been so long that we'll just ignore this issue for now.

We are unable to migrate to Bolt at this time due to time constraints, but will definitely look into doing so in the future. Looks easy enough and migrating Databases is available which is very nice.

Cheers! :)

**Comment by pop4959** [comment]
Absolutely. Just want to keep you in the loop, especially for the reasons I'm closing this out. By the time you find the time to switch I'm sure most of the features you would be interested in will have been ported fully.

LWC of course will still be supported, but I am just focusing less on some of the niche problems that have already been addressed in the design of the new plugin.
