### ISSUE TITLE
Towny support

### ISSUE THREAD

**Issue by Mitsu13Ion** [pop4959/LWCX#22]
**LWC Version (/lwc admin version):** 
2.1.4-6df9204
**Server version (/version):** 
This server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Short five word summary of issue:** 
Towny support don't work

**Detailed description of problem:**
Towny support in wilderness don't work player can always /lock their chest

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
Please update your LWC version as yours is very outdated. You can get the latest one (2.1.8) here: https://www.spigotmc.org/resources/lwc-extended.69551/. Also check that you have enabled the factions integration in your config.

If you have done both, and the problem still exists, please explain clearly what is broken. What has worked before, that now isn't working the way you are expecting it to? You should be able to give exact steps of how to replicate this behavior so that it can be investigated.

**Comment by pop4959** [comment]
Closing due to lack of response.
