### ISSUE TITLE
Lwc admin cleanup get crash

### ISSUE THREAD

**Issue by JohOply** [pop4959/LWCX#23]
**LWC Version (/lwc admin version):** 2.1.9-dev-9cfdb32
**Server version (/version):** git-Spigot-1a3504a-84f3da3 (MC: 1.13.2)

**Short five word summary of issue:** The cleanup command get server crash

**Detailed description of problem:**
The cleanup command get server crash

**If there was an error in console, put it here:**
```
https://pastebin.com/291g8xtK
```

**Comment by pop4959** [comment]
CraftBukkit/Spigot does not support asynchronous chunk loading in your version of MineCraft, which is required for the admin cleanup utility. It should work properly if you upgrade to Paper for MC 1.13, or CraftBukkit/Spigot/Paper for MC 1.14.

**Comment by JohOply** [comment]
Okay, I plan to use Paper when I'll update to 1.14

**Comment by pop4959** [comment]
Sounds good. Thanks for understanding the situation. If you are not using Paper normally on 1.13 due to complications (such as conflicts with plugins) on your server, you can still temporarily use it just to run cleanup, and still use Spigot otherwise. Since cleanup is not needed often, and is also best run without players online, this should be quite an acceptable workaround.

**Comment by JohOply** [comment]
Thanks for these advices
