### ISSUE TITLE
lwc.mod Permission Inoperable

### ISSUE THREAD

**Issue by MysterClaudy** [pop4959/LWCX#3]
**LWC Version (/lwc admin version):** 
2.1.5-09ad392

**Server version (/version):** 
1.14.3-R0.1-SNAPSHOT

**Short five word summary of issue:** 
Permission lwc.mod does not work.

**Detailed description of problem:**
As stated in the Modern-LWC wiki lwc.mod is supposed to allow the player to open any LWC protection. This is currently non-operational and does not allow the player with the given permission to access any any LWC protection and proceeds to give a message to which the chest is locked.

**If there was an error in console, put it here:**
No console error

**Comment by pop4959** [comment]
Actually, upon inspection, this appears to be intentional (however slightly confusing). You can see on the line below that lwc moderators are NOT able to access protections that are owned by lwc admins. That would likely be your issue.

https://github.com/pop4959/Modern-LWC/blob/09ad392a7641fa75daf8469c96b42d8ee90deb71/src/main/java/com/griefcraft/lwc/LWC.java#L765
