### ISSUE TITLE
LWC Error - Primary key

### ISSUE THREAD

**Issue by JohOply** [pop4959/LWCX#39]
**LWC Version (/lwc admin version):** 2.2.0-634f860
**Server version (/version):** git-Spigot-1a3504a-84f3da3 (MC: 1.13.2)

**Short five word summary of issue:** 
Error on /cprivate

**Detailed description of problem:**
Player tried to /cprivate a chest, but plugin seems try to attribute to him a primary key already used. But each time, it incremented number
After some tries, number used as primary key is available and /cprivate works without any error

**If there was an error in console, put it here:**
https://pastebin.com/a2xd2LfM

**Comment by pop4959** [comment]
Did you modify the database by hand at some point? If not, check the server log and see if there was any error when LWC started up. Also, did this happen just once, or persistently, after it fixed itself?

**Comment by JohOply** [comment]
I didn't modify anything on the database

I'm currently not able to test/check (i'm away)

**Comment by pop4959** [comment]
OK, sounds good, take your time. I asked because the only occurrence of this error has been due to server owners manually altering the blocks table. Perhaps you have had some more exceptional condition. It may help to take a look at the blocks table for anything that appears strange. However, if there is nothing really broken with it, it's not unlikely that this issue may fix itself automatically once the keys are no longer duplicate, or when you restart the server.

**Comment by pop4959** [comment]
Closing the issue since there is not been any activity in over 3 months. Can re-open if there is enough information available to warrant investigating this further.
