### ISSUE TITLE
LWC's PlotSquared Support

### ISSUE THREAD

**Issue by ArifErdoganK** [pop4959/LWCX#40]
**LWC Version**: 1.9.7 
**Server Version**: 1.8.8 (PaperSpigot v1.8.8-R0.1-SNAP)*

**Short five word summary of issue**: 
Ability to remove previously existing locks on the plot when acquiring a plot.

**Detailed description of problem**:
Hi!

Can you support PlotSquared, a plot plugin used by me and many other server owners?

When a player buys a plot from another player, unfortunately they cannot open the locked chests in advance and they have to reach us.

PlotSquared's buy plotting commands: "/plotsquared:plotsquared buy and "/plotsquared:plotsquared claim" or  "/plot buy and "/plot claim"

**Comment by pop4959** [comment]
Not sure if that makes sense to me. That could be abused to steal from players (by claiming land on their chests) if I'm not misunderstanding this. LWC has integration with other plugins, but the only purpose is to prevent people from locking blocks inside of claims.

**Comment by ArifErdoganK** [comment]
When a player buys a plot of land for sale by another player, he is unable to open the locks  player must reach the authorities every time. If you cannot provide support for this, I will not be able to use your plugin so that anyone who uses PlotSquared and etc plotme plugins will not.

**Comment by pop4959** [comment]
No need to be tense, I am simply explaining that unlocking things automatically can have a negative side effect which may be undesirable on many servers. I would imagine most servers would not want PlotSquared claiming to be used as an exploit in order to access LWC protections... do you disagree?

Just to clarify, the thing you want to have happen is unlock all chests when someone claims or buys, correct? It might make sense for buy, since I assume there, another player must agree to sell the land. Although, in any case, this is something that LWC typically does not handle. Is the PlotSquared developer active? I may be able to contact them or throw a PR their way if it seems suitable.

**Comment by ArifErdoganK** [comment]
Yes PlotSquared developers are active. Please provide a feature for this. 

Thanks for be interested.

**Comment by pop4959** [comment]
Assuming this is closed on accident... will re-open so we can still keep track of it. I'll look into it.

**Comment by ArifErdoganK** [comment]
Problem was solved when I followed your instructions. Thank you. :heart:
