### ISSUE TITLE
lwc.shownotices toggle command

### ISSUE THREAD

**Issue by burturt** [pop4959/LWCX#48]
Since this can get a bit annoying when opening many locked blocks, can there be a command like /lwc admin togglenotice that toggles between showing and not showing the message?

**Comment by pop4959** [comment]
See the settings in core.yml for notices to set your preferences, or disable the permission if you do not want to view them. You can also check the setting for using the action bar, in case you do not want the messages displaying in main chat repeatedly (only one message can be in the action bar at once). I'm assuming one of those options will fit your use case.

**Comment by burturt** [comment]
Sorry, but I can't seem to find the setting to have the message sent in the action bar. Where is that?
Also thanks for the quick reply!

**Comment by pop4959** [comment]
core.useActionBarSent from my Samsung Galaxy smartphone.
-------- Original message --------From: burturt <notifications@github.com> Date: 10/8/19  17:54  (GMT-08:00) To: pop4959/LWCX <LWCX@noreply.github.com> Cc: pop4959 <pop4959@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [pop4959/LWCX] lwc.shownotices toggle command (#48) Sorry, but I can't seem to find the setting to have the message sent in the action bar. Where is that?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pop4959/LWCX/issues/48?email_source=notifications\u0026email_token=AEHA6EBLXVUHZ5S7URW3VYDQNUTTFA5CNFSM4I6YNP22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAWDM5A#issuecomment-539768436",
"url": "https://github.com/pop4959/LWCX/issues/48?email_source=notifications\u0026email_token=AEHA6EBLXVUHZ5S7URW3VYDQNUTTFA5CNFSM4I6YNP22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAWDM5A#issuecomment-539768436",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pop4959** [comment]
`core.useActionBar`
