### ISSUE TITLE
Hopper protection not working

### ISSUE THREAD

**Issue by BetaBurnt** [pop4959/LWCX#50]
**LWC Version (/lwc admin version):** 
14.11 14:48:20 [Multicraft] admin ran command: lwc admin version
14.11 14:48:20 [Server] INFO LWC 
14.11 14:48:20 [Server] INFO https://www.spigotmc.org/resources/lwc-extended.69551/ 
14.11 14:48:20 [Server] INFO Main plugin: 2.2.2-19d7c70/

**Server version (/version):** 
14.11 14:48:45 [Multicraft] admin ran command: ver
14.11 14:48:45 [Server] INFO This server is running Paper version git-Paper-652 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
14.11 14:48:45 [Server] INFO Previous version: git-Paper-650 (MC: 1.13.2)
14.11 14:48:45 [Server] INFO Checking version, please wait...
14.11 14:48:46 [Server] INFO You are running the latest version

**Short five word summary of issue:** 
Hopper protection is not working.

**Detailed description of problem:**
Placing a hopper next to a locked chest, with `protections.denyHoppers` enabled in the core.yml, does not stop the hopper from adding to/taking from the chests contents (same for furnaces) even if they are locked (without needing to `/chopper on` for the locked block).
Checking the locked chest/furnace with `/cinfo` doesn't report any flags having been applied so it should be following what it says in the config but it's not, and if you do `/chopper off`and punch the chest/furnace it doesn't change the flags on the block either to disable it

Core.yml if needed: https://pastebin.com/XmnqzALV

**Comment by calumari** [comment]
Have you disabled InventoryMoveItemEvent for hoppers in paper.yml?
> hopper:
>   disable-move-event: **false**

**Comment by BetaBurnt** [comment]
.....is that a new paper addition? I haven't changed the server configs for months and this issue has only recently started (at least as far as I'm aware, my players aren't the greatest at reporting issues...). Either way that was it :L Thanks!

**Comment by pop4959** [comment]
As 2277 mentioned, enabling disable-move-event is known to cause issues, and even the Paper documentation acknowledges its use for protections:

![image](https://user-images.githubusercontent.com/17698576/68895179-a42a5c00-06dd-11ea-9aff-ae7c1ff32691.png)

In the latest version, which you have, there is a new experimental config option called alternative hopper protection which will completely block placement of hoppers next to protected items they don't have access to instead of using the event. Keep in mind that it still does not apply to hopper minecarts (since they move), so there is currently not a way to completely avoid using the event without losing some security on your server. Still consider trying it if you're concerned about hoppers causing too much lag in LWC, as it should certainly reduce it.
