### ISSUE TITLE
Unexpected flag specification

### ISSUE THREAD

**Issue by syokkendesuyo** [pop4959/LWCX#52]
For example, when "/ lwc flag a on" is executed, "autoclose" is selected from the registration order.
Should I delete `flag.toString (). toLowerCase (). startsWith (flagName.toLowerCase ())` ?

https://github.com/pop4959/LWCX/blob/19d7c7090d399ffd94f179ef2acb9b5845ff2aa8/src/main/java/com/griefcraft/modules/flag/BaseFlagModule.java#L139

**Comment by pop4959** [comment]
We should probably keep it since it appears to be an intentional shortcut. This allows people to type part of the flag name in the command, while still matching it. It might be ambiguous for flags that all start with the same character(s), but that should be expected.

Feel free to edit the public wiki if you find something that is missing. There are many things that have not been properly documented over the years, or may have been forgotten in the long history of the plugin.

**Comment by pop4959** [comment]
I think I see what you mean now with the PR. So before it was not even showing what flag was selected. Good change. :+1:

**Comment by syokkendesuyo** [comment]
@pop4959 Thank you for the merge!
