### ISSUE TITLE
Prevent players who aren't in your town from locking your chests

### ISSUE THREAD

**Issue by jakkuh** [pop4959/LWCX#58]
**LWC Version (/lwc admin version):** 1.9.7
**Server version (/version):** 1.12.2 Paper 1618

**Short five word summary of issue:** 
Prevent outside players from locking

**Detailed description of problem:**
Some people like to leave chests unlocked so people in their town can use them, but then it's possible for random players to come by and lock them even if they're not in their town.

It would be really nice to have an option to check with the Towny API to see if you own or at least have permissions to the plot before locking something.

**Comment by pop4959** [comment]
I haven't used Towny in a long long time, but remind me: can players place chests in towns that they are not a member of? Assuming that the answer there is no and that you have the "townyBorders" option set, I could see why this would be strange and something to look at improving.

Also, can you double check what versions you are using? The one you mentioned doesn't actually load properly on 1.12.2, because the lowest version supported for it is 1.13.0.

**Comment by jakkuh** [comment]
No, players aren't allowed to interact with most things in other peoples towns unless they are part of the town. I do have the townyBorders option enabled, however this is only to prevent locked chests in the wild. 

You're correct, I'm using 1.9.7

**Comment by pop4959** [comment]
So it sounds like this would be better as it's own config option, rather than being a part of townyBorders since some servers may wish to have chests in the wild, but still not allow locking chests in towns they don't belong to. Does this sound correct?

**Comment by jakkuh** [comment]
Correct!

**Comment by pop4959** [comment]
I just tested this; it seems like players who are not residents are not able to lock blocks in a town. So it appears to be working correctly already?

**Comment by jakkuh** [comment]
Did you test it on 1.12.2?

We just tested it again and both players who are not a member of any town, as well as players who are residents of other towns, can both lock chests in towns they are not members of.

**Comment by pop4959** [comment]
I found the issue; the problem was that c1d515fedb5e532070044163873bcc3632fee483 was never applied to the old version of LWC. This is fixed now via an identical diff d7c3f9c90a606df9310fa5583ba474fe07751e8b for that version.

You can download the build that contains the fix here:
<https://ci.codemc.io/job/pop4959/job/LWCX-legacy/2/>

**Comment by jakkuh** [comment]
It works on 1.12.2 now as well as newer versions, however, if someone has an embassy plot in their town, and someone out of town claims the embassy (as the feature intends), they then cannot claim containers with LWCX.

Also, when someone is denied locking of a chest (like if they are not a member of a town), they're told "You can only protect blocks using LWC inside of a Town!". It seems this is the same error message given when trying to lock a chest in the wilderness and may be a bit confusing to players. Maybe this should be changed to "You can only protect blocks using LWC in your own Town!"

So that's something that would be nice to fix in the future.
