### ISSUE TITLE
Add /clearprotections or similar for Towny

### ISSUE THREAD

**Issue by jakkuh** [pop4959/LWCX#60]
**LWC Version (/lwc admin version):** 1.9.7
**Server version (/version):** 1.12.2 (paper 1618)

**Short five word summary of issue:** 
add command to remove protections in plot

**Detailed description of problem:**
We're having a problem on our Towny server where we have to have mods remove LWC protections from towns for the town owners when a user leaves the town. 

It would be really nice if LWC could hook into Towny and offer a /clearprotections command, that would remove all LWC protections from the current towny plot. It would be good to have a permission for the command so we can allocate it only to specific town roles (ie. make it so mayors and maybe assistants can use). However, it would also need to check if the command issuer was that rank in the town of the plot they're currently standing (so random people cant just go around in other towns removing all the protections).

I'm willing to put a $50 USD bounty to get this feature added asap ahahaha.

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
Do you have WorldGuard on the server? I'm assuming Towny uses cuboid regions, so you could use WE/WG to purge protections in a region with the command `/lwc admin purgeregion <region>`.

**Comment by pop4959** [comment]
Please download and test the latest development build. I have enabled a feature that will remove protections when the town is unclaimed.

Keep in mind that the latest version doesn't support 1.12.2 though. You'll need to use a 1.13 (or newer) server to test this. I don't mind porting it back to the old version, but I'll only do this when you have confirmed that the feature works properly, because it's more tedious otherwise.

**Comment by jakkuh** [comment]
Does this feature remove protections when a plot is unclaimed by a resident as well (but still owned by the town)? Or only when a town unclaims a plot from the world.

**Comment by pop4959** [comment]
It should remove the protections from the plot when it is unclaimed. Please feel free to test if it works as intended.

**Comment by pop4959** [comment]
@jakkuh I saw you made a new issue. Can you confirm that this feature is/isn't working properly?

**Comment by jakkuh** [comment]
Okay so, when a **town** unclaims a plot (/town unclaim) and opens it back up as wilderness, protections are correctly removed.

However, when a player in a town unclaims a plot (/plot unclaim) from their personal ownership (but the town still owns the land), protections do not appear to be removed. This should be corrected, as if someone unclaims a plot in town to give it to someone else, all their protections will be still there.

Also, you should implement the removing of all of a players protections that are within town borders if a town member leaves or is kicked from the town.

**Comment by pop4959** [comment]
Ah I see. So there is some distinction between the town and plot being unclaimed, and it isn't running the cleanup for both. I'll try to look into why that's happening later.

Good note on leaving / getting kicked, I'll keep that in mind as well.

**Comment by pop4959** [comment]
@jakkuh Try the latest development build. I spoke to LlmDl briefly and changed this so it only removes protections on plot clear. So it is up to the mayor to handle it.

**Comment by jakkuh** [comment]
Tested with the latest development build and this does indeed work! :D

Thanks so much for your hard work! Now we just need it backported to a version a server can actually run on :P We use 1.12.2 and it's the biggest version after 1.15 and 1.14 (and 1.8 although most plugins have depreciated it now).

https://drive.google.com/a/linusmediagroup.com/uc?id=14lkstb-VWm4WktL-WU5Yz2mYECH1z_Gi

**Comment by pop4959** [comment]
Excellent! Glad to hear it's working as intended. Maintaining two separate versions of the plugin simultaneously is tedious, which is why most development and testing is done primarily on the latest version. That, and 90%+ of servers using the plugin are running 1.13-1.15 (and less by the day on older versions). I do understand that the original request was to have this feature in the 1.8-1.12 version as well, so I've backported these changes via a870bef74c719b90e512131b0641d68832112f9e for you.

You can find latest builds of LWCX for 1.8-1.12 on either the [EcoCityCraft ](https://ci.ecocitycraft.com/view/LWC/job/LWC-Legacy/)or [CodeMC](https://ci.codemc.io/job/pop4959/job/LWCX-legacy/) CI servers.

**Comment by pop4959** [comment]
Re-added automatic protection cleanup for towns when they are unclaimed / deleted in the latest dev build.
