### ISSUE TITLE
[suggestion] Droptransfer whitelist/blacklists

### ISSUE THREAD

**Issue by rayblon** [pop4959/LWCX#63]
Alright, so, droptransfer looks really amazing -- we want people to be able to have buffers like this when they're mining or dungeon running, but we don't want them being able to transfer all their gear and valuables to their transfer chest when they're about to die, for instance. Could we get some expanded configuration for it so we can allow or disallow specific items?  Ideally with the ability to read lore lines, for servers that have custom items.

**Comment by pop4959** [comment]
Will consider, as the use case seems reasonable.

Blacklist is probably best, as I don't really see much reason for a whitelist (renders the mode practically useless). Checking lore per item might be a bit overkill, but would a setting which disables picking up items if they have it sound good? I imagine the concern would be more using droptransfer to items which are unique / have lore, rather than what the item is.

**Comment by rayblon** [comment]
I'm not sure i understand what you mean by disabling picking up items. I assume you mean that droptransfer wouldn't work if they had those items in their inventory? In our case it would probably limit usability  if I'm hearing that right(that said i could see people carrying chests around to address it, stow gear next to you, drop your other stuff, regear). 

Basically, the approach we're hoping to take with it is 'you can declutter your inventory on the fly, but you're carrying your valuables home'... so things like gravel, flint, wood, stone, all the inventory clogging 'junk blocks' can be sent to bulk storage without you needing to make the journey home, at the cost of courting greater risk since you're able to fill your inventory with ores or rare drops instead of carrying home 4 stacks of goodies and 30 stacks of stone. Unique/lored items definitely take precedent as far as things people need to walk home, though.

**Comment by pop4959** [comment]
I would be happy to clarify that. What I meant is with droptransfer mode enabled, you "drop" the items, but then they are "picked up" or "transferred" to the chest you have it enabled on.

The idea I have here is that adding a blacklist would be best, since you can block items which you don't want picked up, but if you don't add anything then it will pick everything up as usual.

In addition, for your second request regarding items with lore, I was thinking that adding a setting which disables picking up any special items such as those with a custom name, lore, or enchantments.

Maybe an example would make more sense:

Let's say we have diamonds on the blacklist, and have disabled picking up special items. Then, droptransfer would not pick up diamonds that are dropped. Let's also say the player has two different sticks in their inventory. One is a fancy stick with a custom name / lore, and the other is just a regular stick. Droptransfer would not pick up the fancy stick (since special items are disabled), but would pick up the regular stick (since sticks are not on our blacklist).

**Comment by rayblon** [comment]
Ah, I see! Thanks for the clarification; that's more or less how I was envisioning it, the phrasing just threw me off a bit. 

There are some item IDs that we'd probably want exempt from the special item disable if a precise name/lore blacklist feature isn't worth the work put in to make it -- things like custom beetroot soups, carrots, potatoes, potions, etc are likely always consumables with low value regardless of what special variants there are, so maybe the special item disable could have an exception list for certain item IDs.

**Comment by pop4959** [comment]
Yeah it should not be too complicated. This is already a very niche use case, which 99% of servers will not need/use. I don't mind adding a general setting for servers that want something like this, but it would be overkill to do more than that. If your server absolutely needs to control for every individual specific item, this is probably the wrong place for that. You may then instead wish to hire a separate developer for your server who can develop and tune things exactly as you require it. I don't mean to belittle your suggestion, but I'm maintaining the plugin in my free time, and I'd like to focus on things that benefit the majority of servers. :smiley:

**Comment by pop4959** [comment]
@rayblon I hope you didn't take anything I said too personally. Do you have any response for the above? Does the feature as I suggested it fit your use case, or is it not enough to be useful at all? Please understand that I'm just trying to avoid [feature creep](https://en.wikipedia.org/wiki/Feature_creep) which seems prevalent in this issue.

**Comment by pop4959** [comment]
Closing due to lack of response.

**Comment by rayblon** [comment]
@pop4959 Oh, for some reason I didn't get the notification for this in my email until just now for some reason. Sorry about that.  It absolutely does suit our use case; the item blacklist as you've described would definitely get it to a place where we'd be comfortable enabling it. I'd say the bare minimum if it came to it would be the blacklist + no fancy items toggle, though the exempt block id list for no fancy items would greatly increase usability in different areas of play all the same.

No offense taken, either. You putting the time in for this request at all is an honor; anything more is just icing on the cake. ;p
