### ISSUE TITLE
Server lag and error

### ISSUE THREAD

**Issue by TheNety** [pop4959/LWCX#64]
**LWC Version (/lwc admin version):** 2.2.3-9cd94a
**Server version (/version):** Paper 1.13.2 latest build

**Detailed description of problem:**
The server lagged and there occured this error in console https://pastebin.com/QzKBzSH2
There were no LWC commands run before the error

**Comment by pop4959** [comment]
Please note that the top line in the stack trace relates to SQLite and not LWC. While it's true that it froze while trying to do something in LWC, the real problem is your database. This type of issue is only fixable on your end, if you figure out why your database is getting stuck. It's more unusual to see something like this for SQLite vs MySQL but try restarting the server to see if the problem persists. If it does please come on the Discord server and we can try to figure out why.

**Comment by pop4959** [comment]
The [MOSS Discord server](https://discord.gg/PHpuzZS) has channels dedicated to LWC support. I will usually respond within 24 hours, and it's much easier to figure out issues such as these there, where the problem is usually related to server setup rather than the plugin itself. Just let me know you're Nety01 from Github and I'll try to help you out if you're still struggling with this.

**Comment by TheNety** [comment]
Looks like that the problem was temporary, didn't see that error anymore. Thanks for help anyway, if the error would occur again I will contact you on discord.

**Comment by pop4959** [comment]
Sounds good, glad to hear this was a one-off problem :+1:
