### ISSUE TITLE
LWC killed DB connection.

### ISSUE THREAD

**Issue by andrewkm** [pop4959/LWCX#84]
LWC recently killed our DB connection.
Paper 105, LWC latest (built against https://github.com/pop4959/LWCX/commit/f2a5009620356a5b54ffa919cd711f1d3c40467d)

When it happened:
https://pastebin.com/raw/kB1JB5YB

Really weird, only thing I found remotely similar was:
https://github.com/pop4959/LWCX/issues/45

Uptime was 6 days and 4 hours, (longest we've ever really gone due to my absence) but our wait_timeout is literally 7 days...

Am a little confusiousss... anything jump out at you?

**Comment by pop4959** [comment]
Yeah so from all of my investigation into this vein of issue, it is almost certainly a problem with the database, and not LWC itself.

Most likely (although this is just my interpretation of the error), connection was lost to the database while it was reading data. This would explain why it crashed due to timeout on the read0 method, as well as the last packet having been received very briefly before the error.

I don't think you can do more than make sure that your database is stable and online. If this is the one and only time you've seen this error, I wouldn't get too concerned.

**Comment by andrewkm** [comment]
Was indeed the only time in years beyond years. :)
DB machine is definitely in perfect working order and a proper setup.

Hopefully was a one off.
