### ISSUE TITLE
Haven't seen entity lock for a while, when will come?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [pop4959/LWCX#86]
https://github.com/pop4959/LWCX/wiki/Entity-Locking  
it says "Entity locking is currently being redeveloped and is not supported."

Because these days they really shoot too much item frame and caused item lose...

**Comment by pop4959** [comment]
There is no ETA for it. It will happen if and when I have the free time to do it. Also, I have not removed any of the existing entity locking features so it can still be used if you absolutely must. It just has the same bugs and issues as it always has (which is why it isn't recommended). Try using a plugin like CoreProtect to roll back killed mobs, as that will probably work more reliably.
