### ISSUE TITLE
Phantom privates

### ISSUE THREAD

**Issue by rumickon** [pop4959/LWCX#94]
**LWC Version (/lwc admin version): 2.2.5-67bdb89** 
**Server version (/version): Paper-156 (MC: 1.15.2)** 

**Description of problem:** 
Private is not unregistered after breaking the door.

**Comment by pop4959** [comment]
Any more details? This isn't a known bug, so perhaps it is a plugin conflict or issue with your database.

**Comment by rumickon** [comment]
If setting "ignoreBlockDestruction: false" and some one break door, row in database are not removing.

**Comment by pop4959** [comment]
Without any other plugins installed? Can you upload your core.yml file, so that I can try this with your config.

**Comment by rumickon** [comment]
1. After testing, I found that it was due to the setting "ignoreExplosions: true" and tnt explosion or EnderDragon eating. May be it fine.

2. So how I can let the dragon eat blocks and removing privates automatically?

3. When breaking bottom sand on a picture. The door breaks too without removing private.
![sand](https://user-images.githubusercontent.com/3456248/78473279-f4b35c00-7747-11ea-8593-eb5af58eed69.png)

**Comment by pop4959** [comment]
@rumickon Ah I see. While it's actually normal for protections to remain when removed by other plugins (for example, WorldEdit, unless you manually remove protections on the region as well, or CoreProtect), the issue with Ender Dragons is new. I'll try to look into it.

For now, I would recommend using [`/lwc admin cleanup`](https://github.com/pop4959/LWCX/wiki/Protection-cleanup) to solve your issue. This is the command that is normally used to fix protection removal caused by other plugins, but it should be applicable to your current problem as well. This is best run when you are doing your server maintenance, as it may cause additional lag and/or warnings in the console while players are online (depending on your server/database configuration).

**Comment by pop4959** [comment]
I've looked into this some more, and it seems like ender dragons cause explosions, just like creepers do, which is what causes blocks to break. So this is already handled, and controlled by the `ignoreExplosions` config option. This is not considered a normal block break, so it is not removed automatically (more likely for performance reasons). You can still get rid of them with the cleanup command as I've described above.
