### ISSUE TITLE
Feature: Optional config to allow admins to also break protected

### ISSUE THREAD

**Issue by zacholade** [pop4959/LWCX#95]
Hello! This is a feature request to make using this already fantastic plugin (thank you) even more fluid and less disruptive for servers and their players. I believe this plugin, along with all plugins should follow [The Rule of Least Surprise](http://www.catb.org/esr/writings/taoup/html/ch11s01.html), and that is what this feature(s) ultimately aims to achieve.

The first general principle of this feature request is to add an additional variable to the configuration file, `core.yml` which controls whether player admins (added through using the `/cmodify <@username>`) can destroy the protected block as well as the pre-existing owner. This ultimately gives admins joint ownership of the chest, so presumably would also give them permission to modify the protected container's flags and so on.

A tentative name for this variable could be `adminsHaveOwnerPemissions: boolean` (default false of course).

Secondly, a further extension of this idea would be to allow users to configure other users (and/or groups?) which automatically have either admin or regular rights over a protected block. Potentially through the form of a command with a straightforward and already familiar interface: `/cdefaultrights username`, with the ability to prepend either `@` or `-` to the username to distinguish between admins, regular rights and removing. Using just `/cdefaultrights` would show the players which they've configured to have either normal/admin rights. 

This links back to where I referenced the rule of least surprise. Players should be able to completely forget that this protection plugin is doing what it is doing in the background. An initial command to add their friends and *bam*, everything is set and nothing to worry about from there on out. There should be no having to ask friends to break protected containers, or adding their friend again upon placing a new protected container (although the option is there if they would like to). In addition to this rule: why are users asked to use `/cremove` when switching between public, private, password, donation and display container types. There's probably a good reason why in the backend of the plugin which I completely appreciate. However, perhaps wrapping `cremove`'s functionality should be automatic when calling a different protection type on a container with a pre-existing protection type, thereby meaning players aren't expected to use two commands: `cremove` followed by the new protection type to achieve something which should only take one command.

Several potential points to potentially consider if these ideas implemented (will add to this as further points come to mind):
- If `adminsHaveOwnerPemissions` is enabled; should notices also display admins alongside the true owner, ultimately treating them as owners too? `Notice: That Private Chest is locked by <username1>, <username2>... <username3>...`

Thanks you for your time in reading this feature request. I realise it's a lot to consider (sorry). Thanks for your great work in maintaining this already great plugin! I look forward to hearing both yours and the community's thoughts. :)

**Comment by pop4959** [comment]
I generally agree with the rule of least surprise (I didn't know that was a term though) although since LWC is an old plugin, most of the interface is stuck the way it is without surprising users with major changes. This doesn't mean improvements can't be made, however.

As discussed on Discord, I think having a configuration option to allow admins to break chests seems reasonable enough. This could be disabled by default, but I imagine several servers could find a preference for enabling it. I'll certainly take a look to see if this is easily doable with the way the plugin is designed.

Before I continue, please note that generally when making issues you want to make one issue per request. This is so that individual issues can be opened and closed without needing to worry about its constituents.

Default access rights are something that I've already determined will never be realistically possible for inclusion within LWC itself. While LWC does include many command such as `/cpersist` and good support for protection modification via `/lock` and `/cmodify`, there are issues (mostly performance related) with accessing and modifying all of a player's protections at once. These issues probably will not be addressed except for in a complete plugin rewrite, which is not likely. The only commands that operate on all of a player's protections simultaneously are generally `/cadmin` commands. However, this has been a popular request (see #24), and as a result I have released the LWCTrust plugin to do something similar. It allows for default access rights (non-admin however) through the use of trust lists, which bypasses the ACL, and thus does not cause any performance issues.

To answer your next question, it is entirely unnecessary to `/unlock` or `/cremove` a protection to change its type. The correct method of changing a protection that already exists is to use `/cmodify` with the protection type to change to. For example, `/cmodify display` would change the current protection type to the Display type in a single command. Current versions of LWC after update 2.1.8 have automatic completion for protection types as part of the command.

Good point on the notices, but I think admins should still be discrete from owners. It may make sense, but I'll leave it up to what makes sense when looking into your original feature request.

No worries about this being long. Although, as mentioned, you do generally want to make only one issue per idea (be that a feature request, bug report, or question). This generally helps significantly and keeps things coherent. I will say I much prefer an issue like this than one that fails to provide enough detail.

**Comment by zacholade** [comment]
Hello. Thanks for the detailed reply. I've noted your points about raising issues and will make sure to if I necessary in the future. I'll rename this issue appropriately. Appreciate your efforts to try and add the initial discussed ideas! Couldn't thank you enough if it is implemented.

Also, thanks for clarifying everything in your response. I genuinely didn't realise LWC-Trust is a thing. Will add it to my server immediately (thanks)! As for using `/cmodify` to switch between different protection types, that also works great; thank you. I am surprised no one on my server has noticed this was possible before now, so thanks for sharing that trick.

**Comment by pop4959** [comment]
I've looked into this issue, but determined that this is probably too much of a pain to change currently due to how LWC is designed (in addition to the fact that I'm not particularly fond of the change to begin with). The protection "admin" stuff seems to pertain only to modification, and doesn't actually have bearings in destroying protections. When LWC checks for access, it looks to see that you're the owner, or an LWC admin.

Let's let the owner remain in control of their protections. I know there may be reasons for wanting the protection admin to be able to break it, but most of the reasons I can think of boil down to the owner being inactive. If this is the case, an LWC admin can easily `/lwc admin expire` to get rid of them, or `/lwc admin forceownerall` to transfer their protections to a suitable new owner.
