### ISSUE TITLE
Cmodify doesn't work for everything

### ISSUE THREAD

**Issue by muzak23** [pop4959/LWCX#98]
**LWC Version (/lwc admin version):** 
Main plugin: 2.2.5-67bdb89/
**Server version (/version):** 
This server is running Tuinity version git-Tuinity-"003c5b3" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**Short five word summary of issue:** 
cmodify on cdisplay/cdonation bugged
**Detailed description of problem:**
Players cannot give access to others with /cmodify on /cdisplay and /cdonation protections. It doesn't seem like its a bug just something missed.

**If there was an error in console, put it here:**
No errors

**Comment by pop4959** [comment]
I have known this about donation for a while, but hadn't remembered to look into why. Didn't know the same issue occurs with display, but it is probably due to the high shared code between the two. I'll look into this.

It is currently still possible to give people access by making them protection admin, but of course you may not find that ideal compared to normally adding the user since they will be able to modify the protection too.

**Comment by pop4959** [comment]
Added support for this in 857464d3f1aef5b6af319d86f4d81ccad4a7fed2. This will be included in 2.2.6.
