### ISSUE TITLE
Request: Adding an option for magnet to invert the blacklist to a white list

### ISSUE THREAD

**Issue by mvez73** [pop4959/LWCX#99]
Hi. Could you add an option to turn the blacklist of the magnet to a white list? i would like to put only items i choose in the chest. Thanks

**Comment by mvez73** [comment]
Just realised that options are general. Can you make magnet permissions per chest? Thanks

**Comment by pop4959** [comment]
This would be a relatively nontrivial addition to make, because of breakage with old configs and also storing additional information (potentially a lot) on each chest, which is most likely not very storage friendly. Not only that, but I don't think this is an addition that many people need. A blacklist generally makes more sense than a whitelist. A "whitelist" can also be implemented via a hopper sorting system by players, which is a relatively normal thing to do.
